language: cpp
os: osx
compiler: gcc
#cache:
#  directories:
#  - $HOME/build/CARTAvis/CARTAvis-externals/ThirdParty
#  - $HOME/build/CARTAvis/build

#osx_image: xcode7.3 # current default Travis CI xcode version
osx_image: xcode10

jobs:
  include:
    - stage: casacore
      install: true
      script: 
        - ls
        - brew install gcc
#        - brew update
        - brew link --overwrite gcc
#        - brew upgrade
        - brew update
        - brew install fftw numpy hdf5
        - which gfortran
        - echo "Install SOFA"
        - wget http://www.iausofa.org/2018_0130_F/sofa_f-20180130.tar.gz
        - tar xzf sofa_f-20180130.tar.gz
        - cd sofa/20180130/f77/src 
        - make 
        - sudo cp libsofa.a /usr/local/lib/
        - cd ..
        - brew install cfitsio
        - brew install wcslib
        - brew install fftw
#        - brew remove boost
#        - brew uninstall --ignore-dependencies boost
#        - brew upgrade boost # upgrade boost from 1.61.0_1 -> 1.67.0_1
#        - brew install boost --with-python
#        - brew install boost-python
#        - brew install boost-python3
#        - brew install boost-mpi
        - brew install boost-build
#        - brew upgrade boost-python
        - ls -sort /usr/local/lib/libboost*
        - brew install hdf5
#        - ls -sort /usr/local/Cellar
#        - which cmake
#        - cmake --version
#        - brew install cmake
#        - brew upgrade cmake
        - ls /usr/local/Cellar/boost-python
        - cmake --version
        - echo "Set up casacore"
        - git clone https://github.com/casacore/casacore.git
        - mkdir -p casacore/build && cd casacore/build 
        - cmake .. -DUSE_FFTW3=ON -DUSE_HDF5=ON -DUSE_THREADS=ON -DUSE_OPENMP=ON -DDATA_DIR="%CASAROOT%/data" #-DBOOST_ROOT=/usr/local/Cellar/boost-python
        - make -j4
        - sudo make install
        - ls
        - du -hs /usr/local/share/casacore

