language: cpp
os: osx
compiler: clang
osx_image: xcode9.4

## build the frontend

language: node_js
node_js:
  - node

sudo: required

#before_install:
#  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

script:
  - ls
  - git clone https://github.com/idia-astro/carta-frontend.git
  - cd carta-frontend
  - git submodule init
  - git submodule update
  - npm install
#  - docker exec -it emscripten npm install
