language: cpp
os: osx
compiler:
  - clang
  - cpp
#cache:
#  directories:
#  - $HOME/build/CARTAvis/CARTAvis-externals/ThirdParty
#  - $HOME/build/CARTAvis/build

osx_image: xcode9.2 # current default Travis CI xcode version

jobs:
  include:
    - stage: casacore
      install: true
      script: 
        - ls
        - brew install cmake fftw 
        - brew install gcc # so that it can get gfortran
        - brew link gcc
        - echo "Set up casacore"
        - git clone https://github.com/casacore/casacore.git
        - mkdir -p casacore/build && cd casacore/build 
        - cmake .. -DUSE_FFTW3=ON -DUSE_HDF5=ON -DUSE_THREADS=ON -DUSE_OPENMP=ON
        - make -j4
        - sudo make install
        - ls
        - du -hs /usr/local/share/casacore

