language: cpp
os: osx
compiler: clang
osx_image: xcode10

cache:
  directories:
  - $HOME/casacore

before_install:
   - sudo rm /usr/local/include/c++
   - brew install gcc
   - brew install openssl tbb fmt protobuf cfitsio wcslib fftw boost-python hdf5

global:
  - CI_NODE_TOTAL=2 # speed up the build process so the casacore stage can finish in time

jobs:
  include:
    - stage: build casacore
      install: true
      script:
        - cd $HOME
        - ls
        - if [ -e "$HOME/casacore" ]; then echo "casacore cache exists"; else echo "building casacore" && $TRAVIS_BUILD_DIR/scripts/ci_mac_casacore.sh; fi
        - ls -sort

    - stage: build carta-backend
      install: true
      script:
        # copy cached casacore to default system location
        - sudo cp -r $HOME/casacore/lib/* /usr/local/lib/
        - sudo cp -r $HOME/casacore/include/casacore /usr/local/include/
        - cd $HOME

         # echo install libuv
        - git clone https://github.com/libuv/libuv.git
        - cd libuv
        - sh autogen.sh
        - ./configure
        - make -j 2
        - sudo make install
        - cd ..

        # install uWebsockets
        - git clone https://github.com/uNetworking/uWebSockets.git
        - cd uWebsockets
        - git checkout c7aa984 # changing to the old non-'clang'-only Makefile
        - make
        - sudo make install
        - cd ..

        # install zfp
        - git clone https://github.com/LLNL/zfp.git
        - cd zfp && mkdir build && cd build
        - cmake ..
        - make
        - sudo make install
        - cd ../..

        # build carta-backend
        - echo "Building carta-backend" 
        - cd $TRAVIS_BUILD_DIR
        - git submodule init && git submodule update
        - sed -i '' 's/hdf5_serial/hdf5/g' CMakeLists.txt # fix for Mac hdf5 filename
        - sed -i '' 's/target_link_libraries(hdf5_image_viewer/target_link_libraries(hdf5_image_viewer uv/g' CMakeLists.txt # fix to find uv
        - mkdir build && cd build
        - cmake -DCMAKE_CXX_FLAGS="-I /usr/local/Cellar/openssl\@1.1/1.1.1/include" -DCMAKE_CXX_STANDARD_LIBRARIES="-L /usr/local/Cellar/fmt/5.1.0/lib -L /usr/local/Cellar/hdf5/1.10.3/lib -L /usr/local/lib -L /usr/local/Cellar/openssl\@1.1/1.1.1/lib" .. # Might break later when Travis changes version numbers i.e. if the current default openssl 1.1.1 changes to 1.1.2.
        - make
        - ls -sort
        - otool -L hdf5_image_viewer

        - echo "Package carta-backend"

        # install macdylibbundler
        - git clone https://github.com/auriamg/macdylibbundler.git
        - cd macdylibbundler
        - make
        - sudo make install
        - cd ..

        - mkdir -p package/bin && cd package/bin && cp ../../hdf5_image_viewer .
        - cp /usr/local/lib/libuWS.dylib .
        - dylibbundler -od -of -b -d ../libs -x hdf5_image_viewer < $TRAVIS_BUILD_DIR/scripts/keyboard_input.txt
        - rm libuWS.dylib
        - otool -L hdf5_image_viewer
        - ls -sort ../libs/*
        - cd ../..
        - echo $TRAVIS_COMMIT
        - echo $TRAVIS_JOB_ID
        - echo $TRAVIS_JOB_NUMBER
        - mv package package_$TRAVIS_JOB_NUMBER
        - tar -czvf package_$TRAVIS_JOB_NUMBER.tar.gz package_TRAVIS_JOB_NUMBER
        - ls -sort

