language: cpp
os: osx
compiler: clang
osx_image: xcode9.4

## build the frontend

language: node_js
node_js:
  - node

sudo: required

language: objective-c
addons:
  chrome: beta

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - ls
  - git clone https://github.com/idia-astro/carta-frontend.git
  - cd carta-frontend
  - git submodule init
  - git submodule update
  - which emcc 
  - npm install
  - cd wasm_libs
  - ./build_libs.sh
  - cd ..
  - cd wasm_src
  - ./build_wrappers.sh
  - cd ..
  - cd protobuf
  - ./build_proto.sh
  - cd ..
  - npm start
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost:3000 &"

