language: cpp
os: osx
compiler: clang
#cache:
#  directories:
#  - $HOME/build/CARTAvis/CARTAvis-externals/ThirdParty
#  - $HOME/build/CARTAvis/build

osx_image: xcode7.3 # current default Travis CI xcode version

jobs:
  include:
    - stage: casacore
      install: true
      script: 
        - ls
        - brew install cmake fftw wget numpy hdf5
        - brew update
        - brew install gcc
        - brew update
#        - brew upgrade
#        - brew update
        - echo "Install SOFA"
        - wget http://www.iausofa.org/2018_0130_F/sofa_f-20180130.tar.gz
        - tar xzf sofa_f-20180130.tar.gz
        - cd sofa/20180130/f77/src 
        - make 
        - sudo cp libsofa.a /usr/local/lib/
        - cd ..
        - echo "Set up casacore"
        - git clone https://github.com/casacore/casacore.git
        - mkdir -p casacore/build && cd casacore/build 
        - cmake .. -DUSE_FFTW3=ON -DUSE_HDF5=ON -DUSE_THREADS=ON -DUSE_OPENMP=ON
        - make -j4
        - sudo make install
        - ls
        - du -hs /usr/local/share/casacore

