language: cpp
os: osx
compiler: clang

#osx_image: xcode7.3 # current default Travis CI xcode version
osx_image: xcode10

cache:
  directories:
#  - /usr/local/include/casacore
#  - /usr/local/Cellar
  - $HOME/casacore

global:
  - CI_NODE_TOTAL=2 # speed up the build process so the casacore stage can finish in time

jobs:
  include:
    - stage: casacore
      install: true
      script: 
        - ls
        - sudo rm /usr/local/include/c++
        - brew install gcc
        - which gfortran
        - brew install cfitsio wcslib fftw boost-python hdf5
        - echo "Install SOFA"
        - wget http://www.iausofa.org/2018_0130_F/sofa_f-20180130.tar.gz
        - tar xzf sofa_f-20180130.tar.gz
        - cd sofa/20180130/f77/src 
        - make -j 2
        - sudo cp libsofa.a /usr/local/lib/
        - cd ~
        - echo "Install casacore"
        - git clone https://github.com/casacore/casacore.git
        - cd casacore && mkdir build && cd build 
        - ln -s /usr/local/Cellar/boost-python/1.67.0/lib/libboost_python27-mt.dylib /usr/local/lib/libboost_python-mt.dylib  #Fix so that cmake can find the boost-python library file
        - cmake .. -DUSE_FFTW3=ON -DUSE_HDF5=ON -DUSE_THREADS=ON -DUSE_OPENMP=ON -DDATA_DIR="%CASAROOT%/data"
        - make -j 2
#        - sudo make install
        - cd ~
    - stage: carta-backend
      install: true
      script:
        - pwd
        - ls -sort
        - cd casacore/build
        - sudo make install
        - sudo rm /usr/local/include/c++
        - brew install gcc
        - brew install openssl tbb fmt protobuf hdf5
        - ls /usr/local/Cellar/openssl@1.1/
        - git clone https://github.com/libuv/libuv.git
        - cd libuv
        - sh autogen.sh
        - ./configure
        - make -j 2
        - sudo make install
        - cd ..
        - git clone https://github.com/uNetworking/uWebSockets.git
        - cd uWebsockets
        - git checkout c7aa984 # going back to the old non-'clang'-only Makefile
        - make
        - sudo make install
        - cd ..
        - git clone https://github.com/LLNL/zfp.git
        - cd zfp && mkdir build && cd build
        - cmake ..
        - make
        - sudo make install
        - cd ../..
        - echo "Install carta-backend"
        - git submodule init && git submodule update
        - sed -i '' 's/hdf5_serial/hdf5/g' CMakeLists.txt # Fix for Mac hdf5 serial filename
        - mkdir build && cd build
        - cmake -DCMAKE_CXX_FLAGS="-I /usr/local/Cellar/openssl\@1.1/1.1.1/include" ..
        - make
        - make install
        - ls -sort

