language: cpp
os: osx
compiler: clang
osx_image: xcode10.1

## build the frontend
python:
  - 2.7
language: node_js
node_js:
  - "8"

sudo: required

addons:
  chrome: stable

script:
  - brew install llvm cmake python
  - git clone https://github.com/juj/emsdk.git
  - cd emsdk
  - git pull
  - ./emsdk install emscripten-1.38.14
  - ./emsdk activate emscripten-1.38.14
  - source ./emsdk_env.sh
  - cd ..
  - emcc --version
  - npm --version
  - emcc 
  - which emranlib
  - which ranlib
#  - sudo mv /usr/bin/ranlib /usr/bin/ranlib-orig
#  - sudo ln -s /Users/travis/build/ajm-asiaa/travis_test3/emsdk/emscripten/1.38.20/emranlib /usr/bin/ranlib
  - ls
  - git clone https://github.com/idia-astro/carta-frontend.git
  - cd carta-frontend
  - git submodule init
  - git submodule update
  - npm install
  - cd wasm_libs
  - ./build_libs.sh
  - cd ..
  - cd wasm_src
  - ./build_wrappers.sh
  - cd ..
  - cd protobuf
  - ./build_proto.sh
  - cd ..
  - npm start
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost:3000 &"

