version: 2.0
jobs:
  "ubuntu":
    docker:
      - image: ajmasiaa/carta-backend-builder-ubuntu
    steps:
      - checkout
      - run:
          name: "submodules"
          command: |
            git submodule init
            git submodule update
      - run:
          name: "build ubuntu version"
          command: mkdir build && cd build && cmake .. && make && ls && pwd && ./carta_backend &
      - run:
          name: "ICD tests"
          command: ps -aux | grep carta_backend
  "centos6":
    docker:
      - image: ajmasiaa/carta-backend-builder-centos6
    steps:
      - checkout
      - run:
          name: "submodules"
          command: |
            git submodule init
            git submodule update
      - run:
          name: "build CentOS6 version"
          command: source /etc/bashrc && mkdir build && cd build && cmake .. && make && ls

workflows:
  version: 2
  build:
    jobs:
      - "ubuntu"
      - "centos6"
