version: 2.0
jobs:
  "ubuntu":
    docker:
      - image: ajmasiaa/carta-backend-builder-ubuntu
    steps:
      - checkout
      - run:
          name: "submodules"
          command: |
            git submodule init
            git submodule update
      - run:
          name: "build ubuntu version"
          command: mkdir build && cd build && cmake .. && make && ls && pwd
#      - run:
#          name: "run carta_backend in background"
#          command: cd build && ./carta_backend --base ~/carta-backend-ICD-test-travis.tar.gz &
      - run:
          name: "prepare emsdk"
          command: |
            git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && git pull
            ./emsdk install latest
            ./emsdk activate latest
            source ./emsdk_env.sh
      - run:
          name: "ICD tests"
          command: |
            cd emsdk && source ./emsdk_env.sh && cd ..
            which npm
            cd /root/project/build && ls -sort
            wget http://alma.asiaa.sinica.edu.tw/_downloads/carta-backend-ICD-test-travis.tar.gz && tar -xvf carta-backend-ICD-test-travis.tar.gz
            cd /root/project/build && ./carta_backend base=/root/project/carta-backend-ICD-test-travis &
            cd /root/project/build/carta-backend-ICD-test-travis/protobuf && git submodule init && git submodule update && git checkout master && npm install && ./build_proto.sh && cd ..
            npm run test
            echo "Finished !!"
  "centos6":
    docker:
      - image: ajmasiaa/carta-backend-builder-centos6
    steps:
      - checkout
      - run:
          name: "submodules"
          command: |
            git submodule init
            git submodule update
      - run:
          name: "build CentOS6 version"
          command: source /etc/bashrc && mkdir build && cd build && cmake .. && make && ls

workflows:
  version: 2
  build:
    jobs:
      - "ubuntu"
      - "centos6"
